name: CI/CD - Build, Push & Deploy to Self-Hosted Server

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # your remote server (runner) must be registered
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/noir
          docker build -t $IMAGE_NAME:latest .
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ github.sha }}

      # Push both tags
      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/noir
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}

      # Stop and remove old container
      - name: Stop and remove existing container
        run: |
          docker stop noir || true
          docker rm noir || true

      # Pull the new image
      - name: Pull latest image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/noir
          docker pull $IMAGE_NAME:latest

      # Start new container
      - name: Run container
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/noir
          docker run -d --name noir -p 9502:9502 $IMAGE_NAME:latest
      
      # Check self-hosted server
      - name: Show runner host info
        run: |
          echo "Hostname: $(hostname)"
          echo "Current directory: $(pwd)"
          echo "User: $(whoami)"

