name: CI/CD - Build, Push & Deploy to Self-Hosted Server

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # your remote server (runner) must be registered
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image and tag it as "latest" and with commit SHA
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .
          docker tag ghcr.io/${{ github.repository }}:latest ghcr.io/${{ github.repository }}:${{ github.sha }}

      # Push both tags to GHCR
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}

      # Stop and remove old container (if running)
      - name: Stop old container (if any)
        run: |
          docker stop noir || true
          docker rm noir || true

      # Pull latest image
      - name: Pull latest image
        run: docker pull ghcr.io/${{ github.repository }}:latest

      # Run new container
      - name: Run container
        run: |
          docker run -d --name noir -p 80:80 ghcr.io/${{ github.repository }}:latest
